#!/bin/bash
# =============================================================================
# Sincronización de Edge Functions para Supabase Self-Hosted
# Copia las funciones del repositorio al volumen compartido y reinicia edge-runtime
# =============================================================================

set -e

# Colores para output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${BLUE}ℹ️  $1${NC}"; }
log_success() { echo -e "${GREEN}✅ $1${NC}"; }
log_warn() { echo -e "${YELLOW}⚠️  $1${NC}"; }
log_error() { echo -e "${RED}❌ $1${NC}"; }

# === Configuración ===
FUNCTIONS_SOURCE="/app/supabase/functions"
FUNCTIONS_VOLUME="${SUPABASE_FUNCTIONS_VOLUME:-}"
EDGE_RUNTIME_CONTAINER="${EDGE_RUNTIME_CONTAINER:-}"
DOCKER_SOCKET="/var/run/docker.sock"

echo ""
echo "=========================================="
echo "  Sincronización de Edge Functions"
echo "=========================================="
echo ""

# === Validar configuración ===
if [ -z "$FUNCTIONS_VOLUME" ]; then
    log_warn "SUPABASE_FUNCTIONS_VOLUME no está configurado"
    log_info "Configura esta variable en EasyPanel:"
    echo "    SUPABASE_FUNCTIONS_VOLUME=/supabase-functions"
    echo ""
    log_info "Y añade un Mount:"
    echo "    Host: /etc/easypanel/projects/PROYECTO/supabase/code/volumes/functions"
    echo "    Container: /supabase-functions"
    exit 0
fi

if [ ! -d "$FUNCTIONS_SOURCE" ]; then
    log_error "No se encontró el directorio de funciones: $FUNCTIONS_SOURCE"
    exit 1
fi

if [ ! -d "$FUNCTIONS_VOLUME" ]; then
    log_error "El volumen de funciones no existe o no está montado: $FUNCTIONS_VOLUME"
    log_info "Verifica el Mount en EasyPanel"
    exit 1
fi

# === Copiar funciones ===
log_info "Copiando funciones desde $FUNCTIONS_SOURCE a $FUNCTIONS_VOLUME"

FUNCTIONS_COPIED=0
FUNCTIONS_FAILED=0

for fn_dir in "$FUNCTIONS_SOURCE"/*/; do
    if [ -d "$fn_dir" ]; then
        fn_name=$(basename "$fn_dir")
        
        # Crear directorio destino
        mkdir -p "$FUNCTIONS_VOLUME/$fn_name"
        
        # Copiar contenido
        if cp -r "$fn_dir"* "$FUNCTIONS_VOLUME/$fn_name/" 2>/dev/null; then
            log_success "Función copiada: $fn_name"
            ((FUNCTIONS_COPIED++))
        else
            log_error "Error copiando: $fn_name"
            ((FUNCTIONS_FAILED++))
        fi
    fi
done

# Copiar archivos adicionales (version.json, import_map.json, etc.)
for extra_file in "version.json" "import_map.json"; do
    if [ -f "$FUNCTIONS_SOURCE/$extra_file" ]; then
        cp "$FUNCTIONS_SOURCE/$extra_file" "$FUNCTIONS_VOLUME/" 2>/dev/null && \
            log_info "Archivo copiado: $extra_file"
    fi
done

# === Crear _main/index.ts (requerido por edge-runtime para healthcheck) ===
log_info "Creando función _main (healthcheck)"
mkdir -p "$FUNCTIONS_VOLUME/_main"
cat > "$FUNCTIONS_VOLUME/_main/index.ts" << 'EOF'
// Main healthcheck function for edge-runtime
// This file is auto-generated by sync-edge-functions.sh

Deno.serve(async (req) => {
  const url = new URL(req.url);
  
  if (url.pathname === "/_main/health" || url.pathname === "/health") {
    return new Response(JSON.stringify({ status: "ok", timestamp: new Date().toISOString() }), {
      headers: { "Content-Type": "application/json" },
    });
  }
  
  return new Response("Edge Functions Ready", { status: 200 });
});
EOF

echo ""
log_success "Funciones sincronizadas: $FUNCTIONS_COPIED copiadas, $FUNCTIONS_FAILED fallidas"

# === Listar funciones disponibles ===
echo ""
log_info "Funciones disponibles:"
ls -1 "$FUNCTIONS_VOLUME" | while read fn; do
    if [ -d "$FUNCTIONS_VOLUME/$fn" ]; then
        echo "    - $fn"
    fi
done

# === Reiniciar edge-runtime si es posible ===
echo ""
if [ -S "$DOCKER_SOCKET" ]; then
    log_info "Docker socket detectado, intentando reiniciar edge-runtime..."
    
    # Auto-detectar contenedor si no está configurado
    if [ -z "$EDGE_RUNTIME_CONTAINER" ]; then
        # Buscar contenedor que contenga "edge-functions" o "edge-runtime"
        EDGE_RUNTIME_CONTAINER=$(docker ps --format '{{.Names}}' 2>/dev/null | grep -E "(edge-functions|edge-runtime)" | head -1)
    fi
    
    if [ -n "$EDGE_RUNTIME_CONTAINER" ]; then
        if docker restart "$EDGE_RUNTIME_CONTAINER" 2>/dev/null; then
            log_success "Contenedor reiniciado: $EDGE_RUNTIME_CONTAINER"
            echo ""
            log_info "Las Edge Functions estarán disponibles en unos segundos"
        else
            log_warn "No se pudo reiniciar: $EDGE_RUNTIME_CONTAINER"
            log_info "Reinicia manualmente: docker restart $EDGE_RUNTIME_CONTAINER"
        fi
    else
        log_warn "No se encontró contenedor edge-runtime"
        log_info "Configura EDGE_RUNTIME_CONTAINER o reinicia manualmente"
    fi
else
    log_warn "Docker socket no disponible"
    log_info "Para reinicio automático, añade este Mount en EasyPanel:"
    echo "    Host: /var/run/docker.sock"
    echo "    Container: /var/run/docker.sock"
    echo ""
    log_info "O reinicia manualmente:"
    echo "    docker restart <nombre-contenedor-edge-functions>"
fi

echo ""
echo "=========================================="
echo "  Sincronización completada"
echo "=========================================="
echo ""
